name: BridgingPractise
main: cn.ricoco.bridgingpractise.Main
version: "1.3.0-SNAPSHOT"
author: Ricoco
api: ["1.0.0"]
description: A bridging practise plugin helps you practise your bridging ability.

depend:
  - "MemoriesOfTime-GameCore"