name: BridgingPractise
main: cn.ricoco.bridgingpractise.Main
version: "${project.version}"
author: Ricoco
api: ["1.0.0"]
description: A bridging practise plugin helps you practise your bridging ability.